### ISSUE TITLE
waitFor timeout is hardcoded and depends on step duration

### ISSUE THREAD

**Issue by briangough** [Zarkonnen/se-interpreter#32]
The waitFor timer currently does 120 iterations of the step with a 500ms delay.     There are a couple of problems with this
 - the total time can be much more than the script timeout   (120 x (t_step + 500ms))
 - the waiting time can't be controlled with the script timeout

Below is an example of a script that waits for a single non-existent element using a script timeout of 10s and takes over 1300s to terminate. 

I've submitted a patch in https://github.com/Zarkonnen/se-interpreter/pull/31

```
$ time -p node interpreter.js examples/tests/waitForElement_timeout.json
SE-Interpreter 1.0.6
waitForElement_timeout: Starting test (firefox) waitForElement_timeout
waitForElement_timeout: Success {"type":"get","url":"http://saucelabs.com/test/guinea-pig/"}
waitForElement_timeout: Failed [Error: Wait timed out.]
waitForElement_timeout: Test failed: [Error: Wait timed out.]
0/1 tests ran successfully. Exiting
real 1316.17
user 5.68
sys 0.55
```

Here's the example test
```
{
  "type": "script",
  "seleniumVersion": "2",
  "formatVersion": 1,
  "steps": [
    {
      "type": "get",
      "url": "http://saucelabs.com/test/guinea-pig/"
    },
    {
      "type": "waitForElementPresent",
      "locator": {
        "type": "id",
        "value": "nonexistent-element-3998ac91-3b12-453d-a3a7-6a5f66ff5aed"
      }
    }
  ],
  "timeoutSeconds": 10
}
```

**Comment by davidlinse** [comment]
Indeed, this is pretty ugly.. 
@Zarkonnen any news on that ?

**Comment by Zarkonnen** [comment]
Quite, I just missed this issue re:closing. Thanks for bumping it.
