### ISSUE TITLE
headless?

### ISSUE THREAD

**Issue by franklovecchio** [Zarkonnen/se-interpreter#43]
How might I run this headless? I can't quite put the pieces together for using webdriver-manager / selenium on Mac / Ubuntu. Specifying "phantomjs" as the browser doesn't seem to work, and I don't want to use sauce in this instance. I'm using Xvfb + Firefox with this configuration: https://azevedorafaela.wordpress.com/2014/06/20/how-to-run-selenium-headless-browser-in-ubuntu/ .

Thanks!

**Comment by Zarkonnen** [comment]
Yeah, specifying phantom JS as the browser should be the correct way to go about it. What happens when you do? Does it not work? Just use Firefox? Can I see your config?

**Comment by franklovecchio** [comment]
I just ended up using Xvfb, and now everything is hunky-dory. Thanks!

**Comment by tcorral** [comment]
Hi, I tried to open it with PhantomJS but it doesn´t works. Do you have any idea what could be the problem?

Thanks.
