### ISSUE TITLE
SauceLabs UI is setting 'passed' as null

### ISSUE THREAD

**Issue by gregmoser** [Zarkonnen/se-interpreter#51]
I'm not sure if this is just not implemented, but it would be great if the 'passed' value in sauceLabs could be set to 'true or false' if the test passes or not.

**Comment by Zarkonnen** [comment]
Hmm, https://github.com/Zarkonnen/se-interpreter/blob/master/utils/sauce_listener.js#L29 looks like it should do that. I'll verify.

**Comment by gregmoser** [comment]
I'm sorry... I didn't realize that I needed to pass a listener in as a separate command argument.  I re-read the README added the sauce_listener and now it is reporting results.  It is only breaking for the last test in a suite because of the issue I addressed here: https://github.com/Zarkonnen/se-interpreter/pull/54

In addition, is there any way to set the listener in a config json?
