### ISSUE TITLE
Passing a 'Build' to the SauceLabs interface

### ISSUE THREAD

**Issue by gregmoser** [Zarkonnen/se-interpreter#52]
I looked through the documentation, but I didn't see anywhere that I could pass a buildID to the SauceLabs interface.

**Comment by Zarkonnen** [comment]
Sorry, can you expand on this a bit? Where would this buildID come from, and where would it end up with Sauce Labs?

**Comment by gregmoser** [comment]
I think that Sauce now has a new UI where you can pass a 'Build ID': http://screencast.com/t/6cqmOWMtNOQ

**Comment by gregmoser** [comment]
Now that I have the sauce listener working, I realized that I could just create a custom listener based on the default sauce listener and pass a buildID to sauce like this: 

https://github.com/ten24/slatwall/blob/20754a23ce53cafcd79385d289e5aae100317c16/meta/tests/integration/se_sauce_junit_listener.js#L25-L27

**Comment by gregmoser** [comment]
As an update for any future readers... you can just add 'build':'xxx' to the browserOptions.  Much easier!
